server:
  port: 8888
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsps/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/capp?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.jz.tools.sql.entity
 
logging:
  level:
    com:
      jz:
        tools: debug
